### ISSUE TITLE
Not able to run chrome crawler

### ISSUE THREAD

**Issue by Naimadnap** [apiel/test-crawler#23]
When in project settings I set chrome-selenium I get an error

```

Error: Command failed: cd /Users/damian/.config/yarn/global/node_modules/test-crawler && ISOMOR_DIST_SERVER_FOLDER=/Users/damian/.config/yarn/global/node_modules/test-crawler/../test-crawler/dist-server ISOMOR_STATIC_FOLDER=/Users/damian/.config/yarn/global/node_modules/test-crawler/../test-crawler/build npm run isomor:server
    at checkExecSyncError (child_process.js:631:11)
    at execSync (child_process.js:668:15)
    at startTestCrawler (/Users/damian/.config/yarn/global/node_modules/test-crawler/test-crawler.js:22:5)
    at Object.<anonymous> (/Users/damian/.config/yarn/global/node_modules/test-crawler/test-crawler.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
```

selenium-server and chromedriver installed globally
Test-crawler v3.5.6

**Comment by apiel** [comment]
Hi, thx for the report. I am also having issue to run `test-crawler`, unfortunately I don't work on this project anymore. I will try to look at it over the weekend. In case you want to run it before I fix it, you can try to clone the repo, run `npx lerna bootstrap`, then `cd packages/test-crawler/` and finally `yarn test-crawler`. Hopefully this would work.

**Comment by damian-zygmuntowicz-siili** [comment]
@apiel it doesn't help `yarn test-crawler` runs global instance for me

maybe I can install chrome manually
